config/routes.rb
Tester::Application.routes.draw do

  
  root "about#aboutPage"
  get "tour" , to: "tour#tourPage"
  get "contact" => "contact#contactPage"
  get "team" => "team#teamPage"
  get "services" => "services#servicesPage"
  get "pricing" => "pricing#pricingPage"
  get "portfolio" => "portfolio#portfolioPage"

end

app/controllers/about_controller.rb
class AboutController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  	 layout 'about_layout'

	def about
	end	



 end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception



  def home
  end


  def tour  
  end

  def about
  end

  def pricing
  end

  def services
  end

  def contact
  end

  	
end

app/controllers/contact_controller.rb
class ContactController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  	 layout 'contact_layout'

	def contact
	end	



 end
  

app/controllers/pages_controller.rb
class PagesController < ApplicationController


end

app/controllers/portfolio_controller.rb
class PortfolioController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  	 layout 'portfolio_layout'

	def portfolio
	end	



 end
  

app/controllers/pricing_controller.rb
class PricingController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  	 layout 'pricing_layout'

	def pricing
	end	



 end
  

app/controllers/services_controller.rb
class ServicesController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  	 layout 'services_layout'

	def services
	end	



 end
  

app/controllers/team_controller.rb
class TeamController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  	 layout 'team_layout'

	def team
	end	



 end
  

app/controllers/tour_controller.rb
class TourController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  	 layout 'tour_layout'

	def tour
	end	



 end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_about.html.erb
    <body>
       <!-- Rich Snippet Code -->
       <div style = "display:none" itemscope itemtype="http://schema.org/LocalBusiness">
        <a itemprop="url" href="http://www.succinctdesign.co.za/"><div itemprop="name"><strong>Succinct Design</strong></div>
        </a>
        <div itemprop="description">We are a Cape Town based South African startup that offers digital solutions to both businesses and individuals. We offer a wide variety of services from web design and application development to online branding and e-marketing. We can provide the optimal solution to meet your digital needs.</div>
        <div itemprop="address" itemscope itemtype="http://schema.org/PostalAddress">
        <span itemprop="addressLocality">Cape Town</span><br>
        <span itemprop="addressCountry">South Africa</span><br>
        <img itemprop="logo" src="SDjustlogo.png" />
        </div>
      </div>

       <!-- about begins -->
    <section id="page-about" class="page-about">
      <div class="container">
                <header class="section-header">
                    <h2 class="section-title">What We Do</h2>
                    <div class="spacer"></div>
                    <p class="section-subtitle">We are a Cape Town based South African startup that offers digital solutions to both businesses and individuals.  We offer a wide variety of services from web design and application development to online branding and e-marketing. We can provide the optimal solution to meet your digital needs.</p>
                    <%= link_to "Take the tour" , tour_path , class: "btn btn-default" %>
                </header>                     
      </div> 
    </section><!-- about ends -->

    <section id="page-about-research" class="page-about">
      <div class="container">
          <div class="row">
              <div class="col-md-3 text-center">
                <div class="research hi-icon-effect-1">
                  <a href="#page-about-research" ><i class="hi-icon fa fa-flask"></i></a>
                </div>
                <header class="process-header">
                </header>
              </div>
              <div class="col-md-9 text-center">
                <header class="process-header">
                  <h3>Research</h3>
                  <p>Clients come to us with a problem or idea. We examine the situation and try to find as much information as possible. Once we have a thorough understanding of the clients needs, we can move forward and design the best solution.</p>
                </header>
          </div>
      </div>
    </section><!-- about ends -->

        <section id="page-about-design" class="page-about">
      <div class="container">
          <div class="row">
              <div class="col-md-3 text-center">
                <div class="design hi-icon-effect-1">
                  <a href="#page-about-design" ><i class="hi-icon fa fa-pencil-square-o"></i></a>
                </div>
                <header class="process-header">
                </header>
              </div>
              <div class="col-md-9 text-center">
                <header class="process-header">
                  <h3>Design</h3>
                  <p>Once we have direction, we start on our design. By carefully planning and designing the best approach before development, we can save a tremendous amount of both time and effort. This not only makes our job easier but also saves the client costs. </p>
                </header>
          </div>
      </div>
    </section><!-- about ends -->

    <section id="page-about-development" class="page-about">
      <div class="container">
          <div class="row">
              <div class="col-md-3 text-center">
                <div class="research hi-icon-effect-1">
                  <a href="#page-about-development" ><i class="hi-icon fa fa-code"></i></a>
                </div>
                <header class="process-header">
                </header>
              </div>
              <div class="col-md-9 text-center">
                <header class="process-header">
                  <h3>Develop</h3>
                  <p>Using the latest tools, technology and programming languages we can execute our design to develop an amazing product. HTML5, Ruby on Rails, Java, Python, Objective C, Microsoft.Net or any other language that best suits your requirements. </p>
                </header>
          </div>
      </div>
    </section><!-- about ends -->

        <section id="page-about-deploy" class="page-about">
      <div class="container">
          <div class="row">
              <div class="col-md-3 text-center">
                <div class="research hi-icon-effect-1">
                  <a href="#page-about-deploy" ><i class="hi-icon fa fa-rocket"></i></a>
                </div>
                <header class="process-header">
                </header>
              </div>
              <div class="col-md-9 text-center">
                <header class="process-header">
                  <h3>Deploy</h3>
                  <p>Only once the client is 100% satisfied and the product is perfect, do we launch. But it doesn't stop there. We can also help with getting your product noticed with social media and online marketing campaigns.</p>
                </header>
          </div>
      </div>
    </section><!-- about ends -->


        <script src="js/jquery-1.10.2.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/jquery.queryloader2.min.js"></script>
        <script src="js/jquery.scrollTo.js"></script>
        <script src="js/jquery.nav.js"></script>
        <script src="js/jquery.isotope.min.js"></script>
        <script src="js/waypoints.min.js"></script>
        <script src="js/main.js"></script>


    </body>

app/views/layouts/_contact.html.erb
    <body>
    <!-- contact begins -->
     <section id="page-contact" class="page-contact">
          <div class="container">
              <header class="section-header">
                  <h2 class="section-title"><span>Contact</span></h2>
                    <div class="spacer"></div>
                       <p class="section-subtitle">Feel free to contact us with any enquiry.</p>
              </header>
        <div class="row">
          <div class="col-sm-5 contact-info">
            <h3>Contact Info</h3>
            <p><i class="fa fa-map-marker"></i> Cape Town, South Africa</p>
            <p><i class="fa fa-phone"></i> 072 62 34 617 </p>
            <p><i class="fa fa-envelope-o"></i> info@succinctdesign.co.za</p>
            <br>
            <h3>Connect Soccially</h3>
            <p><i class="fa fa-facebook"></i>  Like us on Facebook</p>
            <p><i class="fa fa-twitter"></i>  Follow us on Twitter</p>
            <p><i class="fa fa-linkedin"></i>  Link with us on LinkedIn</p></a>
          </div>
          
          <div class="col-sm-7">
          <h3>Get in Touch</h3>
              <form  cMETHOD=POST ACTION="mailto:info@succinctdesign.co.za" ENCTYPE="text/plain">
        <div class="control-group">
            <label class="control-label" for="name">Name</label>
            <div class="controls">
                <input type="text" name="name" id="name" placeholder="Your name" class="form-control input-lg ">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="email">Email Address</label>
            <div class="controls">
                <input type="text" name="email" id="email" placeholder="Your email address" class="form-control input-lg">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="message">Message</label>
            <div class="controls">
                <textarea name="message" id="message" rows="8" class="form-control input-lg"></textarea>
            </div>
        </div>
        <div class="form-actions">
            <button type="submit" class="btn btn-default btn-lg btn-block">Submit Message</button>
        </div>
    </form><!-- End contact-form -->
          </div>
        </div><!-- End row -->



        </div> 
    </section> <!-- contact ends -->


       <script src="js/jquery-1.10.2.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/jquery.queryloader2.min.js"></script>
        <script src="js/jquery.scrollTo.js"></script>
        <script src="js/jquery.nav.js"></script>
        <script src="js/jquery.isotope.min.js"></script>
        <script src="js/jquery.validate.js"></script>
        <script src="js/waypoints.min.js"></script>
        <script src="js/main.js"></script>


    </body>

app/views/layouts/_footer.html.erb
    <body>
 
    <div id="footer">
      <div class="container">
        <p></p>
          <p class="split-para">
          © 2014. Succinct Design PTY. South Africa.
          <span>
          Follow: <a href="http://twitter.com/succinctdesign" target="_blank"> <i class="fa fa-twitter"></i> </a>
          Like: <a href="http://facebook.com/succinctdesign" target="_blank"> <i class="fa fa-facebook"></i> </a>
          Link: <a href="http://za.linkedin.com/in/succinctdesign/" target="_blank"> <i class="fa fa-linkedin"></i> </a>
          </span>
        </p>
      </div>
    </div>

    </body>

app/views/layouts/_pricing.html.erb
    <body>
                <!-- pricing begins -->
    <section id="page-pricing" class="page-pricing">
      <div class="container">
                <header class="section-header">
                    <h2 class="section-title">Pricing</h2>
                    <div class="spacer"></div>
                    <p class="section-subtitle">Some of our packages available. </p>
                </header>

        <div class="row">
          
          <div id="pricePlans">
            
            <div class="col-md-3">
            <ul id="plan1">
              <li class="plan">
                <ul class="planContainer">
                  <li class="title"><h2>Simple Site</h2></li>
                  <li class="price"><p>R3999+</p></li>
                  <li>
                    <ul class="options">
                      <li>Up to 4 Pages</li>
                      <li>Responsive Design</li>
                      <li>Mobile Version</li>
                      <li>Basic SEO</li>
                      <li>Basic Customization</li>
                    </ul>
                  </li>
                  <li class="button"><a href="/contact">Enquire Now</a></li>
                </ul>
              </li>
              </ul> <!-- End ul#plans -->
            </div>

              <div class="col-md-3">
              <ul id="plan2">
              <li class="plan">
                <ul class="planContainer">
                  <li class="title"><h2 class="bestPlanTitle">Full Site</h2></li>
                  <li class="price"><p class="bestPlanPrice">R9999+</p></li>
                  <li>
                    <ul class="options">
                      <li>Up to 20 Pages</li>
                      <li>Responsive Design</li>
                      <li>Mobile Version</li>
                      <li>Tailored SEO</li>
                      <li>Complete Customization</li>
                    </ul>
                  </li>
                  <li class="button"><a class="bestPlanButton" href="/contact">Enquire Now</a></li>
                </ul>
              </li>
              </ul> <!-- End ul#plans -->
            </div>

              <div class="col-md-3">
                <ul id="plan3">
              <li class="plan">
                <ul class="planContainer">
                  <li class="title"><h2>Web App</h2></li>
                  <li class="price"><p>R12000+</p></li>
                  <li>
                    <ul class="options">
                     <li>Cloud Based</li>
                      <li>Multi-Device</li>
                      <li>Scalable</li>
                      <li>Rapid Development</li>
                      <li>24 Hour Support</li>
                    </ul>
                  </li>
                  <li class="button"><a href="/contact">Enquire Now</a></li>
                </ul>
              </li>
              </ul> <!-- End ul#plans -->
             </div>

               <div class="col-md-3">
              <ul id="plan4">
              <li class="plan">
                <ul class="planContainer">
                  <li class="title"><h2>SEO</h2></li>
                  <li class="price"><p>TBA*</p></li>
                  <li>
                    <ul class="options">
                      <li>Website Audit</li>
                      <li>Optimization</li>
                      <li>Increased Visibility</li>
                      <li>Increased traffic</li>
                      <li>Increased Pagerank</li>
                    </ul>
                  </li>
                  <li class="button"><a href="/contact">Enquire Now</a></li>
                </ul>
              </li>
              </ul> <!-- End ul#plans -->
          </div>

          </div>
        </div>
 
      </div> 
    </section><!-- pricing ends -->              


        <script src="js/jquery-1.10.2.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/jquery.queryloader2.min.js"></script>
        <script src="js/jquery.scrollTo.js"></script>
        <script src="js/jquery.nav.js"></script>
        <script src="js/jquery.sticky.js"></script>
        <script src="js/jquery.isotope.min.js"></script>
        <script src="js/waypoints.min.js"></script>
        <script src="js/main.js"></script>


    </body>

app/views/layouts/_team.html.erb
    <body>
!-- team begins -->
     <section id="page-team" class="page-team">
       <div class="container">
                <header class="section-header">
                    <h2 class="section-title"><span>Our Team</span></h2>
                     <div class="spacer"></div>
                    <p class="section-subtitle">Meet our team of talented individuals.</p>
                </header>
                <div class="row"> 
                 <div class="col-md-3">
                    <div class="team-block">
                     <div class="photo"><img src="img/team/FelixNorton.gif" alt="Felix Norton, founder of Succinct Design, website designer and apllication developer living in Cape Town, South Africa"></div>
                      <div class="name-team">Felix Norton</div>
                       <div class="team-title">Founder & Developer</div>
                      <div class="team-footer">
                        <div class="follow">
                          <h3>Follow <i class="fa fa-plus-circle"></i></h3>
                       </div>
                        <div class="team-social-icons">
                          <a href="http://twitter.com/" class="btn btn-round btn-clear btn-twitter"><i class="fa fa-twitter"></i></a>
                        <a href="http://www.facebook.com/" class="btn btn-round btn-clear btn-facebook"><i class="fa fa-facebook"></i></a>
                         <a href="http://www.linkedin.com/" class="btn btn-round btn-clear btn-linkedin"><i class="fa fa-linkedin-square"></i></a>
                        </div>
                       </div>
                     
                    
                   </div>
                </div>
             
                <div class="col-md-3">
                     <div class="team-block">
                      <div class="photo"><img src="img/team/willfrancis.gif" alt="William Francis, Systems Developer and consultant at Succinct Design"></div>
                      <div class="name-team">William Francis</div>
                      <div class="team-title">Consulting Developer</div>
                        <div class="team-footer">
                        <div class="follow">
                          <h3>Follow <i class="fa fa-plus-circle"></i></h3>
                       </div>
                        <div class="team-social-icons">
                        <a href="http://twitter.com/" class="btn btn-round btn-clear btn-twitter"><i class="fa fa-twitter"></i></a>
                        <a href="http://www.facebook.com/" class="btn btn-round btn-clear btn-facebook"><i class="fa fa-facebook"></i></a>
                        <a href="http://www.dribbble.com/" class="btn btn-round btn-clear btn-dribbble"><i class="fa fa-dribbble"></i></a>
                         <a href="http://www.linkedin.com/" class="btn btn-round btn-clear btn-linkedin"><i class="fa fa-linkedin-square"></i></a>
                        </div>
                       </div>
                   </div>
                </div>
                <div class="col-md-3">
                       <div class="team-block">
                      <div class="photo"><img src="img/team/Andre.gif" alt="Andre Ogle, Honours graduate from UCT in Information Systems is a programmer and developer at Succinct Design"></div>
                      <div class="name-team">Andre Ogle</div>
                       <div class="team-title">Developer</div>
                        <div class="team-footer">
                        <div class="follow">
                          <h3>Follow <i class="fa fa-plus-circle"></i></h3>
                       </div>
                        <div class="team-social-icons">
                          <a href="http://twitter.com/" class="btn btn-round btn-clear btn-twitter"><i class="fa fa-twitter"></i></a>
                        <a href="http://www.facebook.com/" class="btn btn-round btn-clear btn-facebook"><i class="fa fa-facebook"></i></a>
                        <a href="http://www.dribbble.com/" class="btn btn-round btn-clear btn-dribbble"><i class="fa fa-dribbble"></i></a>
                         <a href="http://www.linkedin.com/" class="btn btn-round btn-clear btn-linkedin"><i class="fa fa-linkedin-square"></i></a>
                        </div>
                       </div>
                   </div>
                </div>
                <div class="col-md-3">
                       <div class="team-block">
                      <div class="photo"><img src="img/team/simon-miller.gif" alt="Simon Miller, video editor and graphic artist at Succinct Design."></div>
                      <div class="name-team">Simon Miller</div>
                     <div class="team-title">Video/Graphic Artist</div>
                        <div class="team-footer">
                        <div class="follow">
                          <h3>Follow <i class="fa fa-plus-circle"></i></h3>
                       </div>
                        <div class="team-social-icons">
                          <a href="http://twitter.com/" class="btn btn-round btn-clear btn-twitter"><i class="fa fa-twitter"></i></a>
                        <a href="http://www.facebook.com/" class="btn btn-round btn-clear btn-facebook"><i class="fa fa-facebook"></i></a>
                        <a href="http://www.dribbble.com/" class="btn btn-round btn-clear btn-dribbble"><i class="fa fa-dribbble"></i></a>
                         <a href="http://www.linkedin.com/" class="btn btn-round btn-clear btn-linkedin"><i class="fa fa-linkedin-square"></i></a>
                        </div>
                       </div>
                   </div>
                </div>
            </div>
        </div>
    </section><!-- team ends -->


        <script src="js/jquery-1.10.2.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/jquery.queryloader2.min.js"></script>
        <script src="js/jquery.parallax-1.1.3.js"></script>
        <script src="js/jquery.scrollTo.js"></script>
        <script src="js/jquery.nav.js"></script>
        <script src="js/jquery.sticky.js"></script>
        <script src="js/jquery.isotope.min.js"></script>
        <script src="js/jquery.magnific-popup.min.js"></script>
        <script src="js/jquery.validate.js"></script>
        <script src="js/waypoints.min.js"></script>
        <script src="js/main.js"></script>


    </body>

app/views/layouts/contact_layout.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Succinct Design - Contact  - Website Design & Application Development</title>
          <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
          <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
          <%= csrf_meta_tags %>

        <meta name="description" content="Get in touch with Succinct Design, Email, Phone, Skype and connect socially with Facebook, Twitter and LinkedIn. Enquire about getting a website design quote, apllication development idea feasibility, SEO audit etc.">
        <meta name="viewport" content="width=device-width, initial-scale=1">    
        <meta name="author" content="">

        <!-- Google Analytics -->
        <script type="text/javascript">
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-48265300-1']);
          //_gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        </script>

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <!-- Fonts from Font Awsome -->
        <link rel="stylesheet" href="css/font-awesome.min.css">
         <!-- Magnific popup -->
        <link rel="stylesheet" href="css/magnific-popup.css">
        <!-- Custom styles for this template -->
        <link rel="stylesheet" href="css/main.css">


        <link rel="stylesheet" href="css/colors/blue.css">
        <!-- <link rel="stylesheet" href="css/colors/blue.css">-->
        <!-- <link rel="stylesheet" href="css/colors/yellow.css">-->
        <!-- <link rel="stylesheet" href="css/colors/purple.css">-->
        <!-- <link rel="stylesheet" href="css/colors/orange.css">-->
        <!-- <link rel="stylesheet" href="css/colors/red.css">-->
        
        <!-- Feature detection -->
        <script src="js/modernizr-2.6.2.min.js"></script>
        <!-- Fonts -->
        <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,900,300italic,400italic,600italic,700italic,900italic' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="js/plugins/html5shiv.js"></script>
          <script src="js/plugins/respond.min.js"></script>
        <![endif]-->
    </head>

    <!-- Render the body -->
    <body>
        <% if Rails.env.production? %>
        <script>_gaq.push(['_trackPageview']);</script>
        <% end %>
    </body> 
    <%= render partial: "layouts/nav" %> 
    <%= render partial: "layouts/contact" %>
    <%= render partial: "layouts/footer" %> 


</html>

app/views/layouts/portfolio_layout.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Succinct Design - Portfolio - Website Design & Application Development</title>
          <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
          <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
          <%= csrf_meta_tags %>

        <meta name="description" content="Succinct Design has a great portfolio of completed and current work. We have many very satisfied customers, you can read some of their testimonials. We have done Website Design, Application Development, Logo and Graphic Design, E-marketing, Search Engine Optimization, Social Media Marketing and more. These companies are all over South Africa, including Cape Town, Durban and Johannesburg.">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="author" content="">

        <!-- Google Analytics -->
        <script type="text/javascript">
          var _gaq = _gaq || [];
          _gaq.push(['_setAccount', 'UA-48265300-1']);
          //_gaq.push(['_trackPageview']);

          (function() {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
          })();
        </script>

        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        <link rel="shortcut icon" href="favicon.ico" type="image/x-icon">

        <!-- Bootstrap core CSS -->
        <link rel="stylesheet" href="css/bootstrap.min.css">
        <!-- Fonts from Font Awsome -->
        <link rel="stylesheet" href="css/font-awesome.min.css">
         <!-- Magnific popup -->
        <link rel="stylesheet" href="css/magnific-popup.css">
        <!-- Custom styles for this template -->
        <link rel="stylesheet" href="css/main.css">


        <link rel="stylesheet" href="css/colors/blue.css">
        <!-- <link rel="stylesheet" href="css/colors/blue.css">-->
        <!-- <link rel="stylesheet" href="css/colors/yellow.css">-->
        <!-- <link rel="stylesheet" href="css/colors/purple.css">-->
        <!-- <link rel="stylesheet" href="css/colors/orange.css">-->
        <!-- <link rel="stylesheet" href="css/colors/red.css">-->
        
        <!-- Feature detection -->
        <script src="js/modernizr-2.6.2.min.js"></script>
        <!-- Fonts -->
        <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,900,300italic,400italic,600italic,700italic,900italic' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="js/plugins/html5shiv.js"></script>
          <script src="js/plugins/respond.min.js"></script>
        <![endif]-->
    </head>

    <!-- Render the body -->
    <body>
        <% if Rails.env.production? %>
        <script>_gaq.push(['_trackPageview']);</script>
        <% end %>
    </body> 
    <%= render partial: "layouts/nav" %> 
    <%= render partial: "layouts/portfolio" %> 
    <%= render partial: "layouts/footer" %>   

</html>